[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dspy-test"
version = "0.1.0"
description = "DSPy"
requires-python = ">=3.11"
dependencies = ["dspy"]

[tool.setuptools]
packages = ["src"]
